# Generated by Django 3.2.5 on 2021-07-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api_app', '0003_auto_20210724_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profile_api_app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profile_api_app.profile'),
            preserve_default=False,
        ),
    ]
