# Generated by Django 3.2.5 on 2022-05-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api_app', '0004_auto_20210729_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img'),
        ),
    ]
